CREATE DEFINER=`root`@`%` FUNCTION `ESG_DB`.`fnCommCdNm`(grpCd VARCHAR(20), cd VARCHAR(20)) RETURNS varchar(250) CHARSET utf8
BEGIN
	DECLARE O_CD_NM VARCHAR(250);

	SELECT CD.CD_NM
	  INTO O_CD_NM
	  FROM CM_COMM_CD_INFO CD
 	 WHERE CD.GRP_CD = grpCd
   	   AND CD.CD = cd;
	
   	  RETURN O_CD_NM;
END;

CREATE DEFINER=`root`@`%` FUNCTION `ESG_DB`.`nextval`(the_name VARCHAR(32)) RETURNS int(10) unsigned
    DETERMINISTIC
BEGIN
	DECLARE ret BIGINT UNSIGNED;
    UPDATE sequences SET currval = currval +1 WHERE name = the_name;
    SELECT currval INTO ret FROM sequences WHERE name = the_name LIMIT 1;
    RETURN ret;
END;

CREATE DEFINER=`root`@`%` PROCEDURE `ESG_DB`.`TableSelectFieldCommentPivot`(IN tableName VARCHAR(255), IN tableAlias VARCHAR(20), IN tableComment VARCHAR(255))
BEGIN
	SET SESSION group_concat_max_len = 100000;

	SELECT CONCAT('SELECT \n'
		, GROUP_CONCAT( ' ', tableAlias, '.', tb.COLUMN_NAME, '\t\t\t\t\t/* ', tb.COLUMN_COMMENT, ' */\n')
		, CONCAT('FROM ', tableName, ' ', tableAlias, '\t\t\t\t\t/* ', tableComment, ' */' ) )
	from information_schema.columns tb
	 where tb.TABLE_SCHEMA = 'ESG_DB'
	   and TABLE_NAME like tableName;
END;

-- ESG_DB.ACT_ANSR_DTL_INFO definition

CREATE TABLE `ACT_ANSR_DTL_INFO` (
  `MBR_UID` int(15) DEFAULT NULL COMMENT '회원채번',
  `ACT_TGT_CD` varchar(20) NOT NULL COMMENT '활동대상코드',
  `STEP_CD` varchar(20) NOT NULL COMMENT '단계코드',
  `SEQ_NO` decimal(5,0) DEFAULT NULL COMMENT '순번',
  `QITEM_GRP_CD` varchar(20) DEFAULT NULL COMMENT '문항그룹코드',
  `QITEM_CD` varchar(20) DEFAULT NULL COMMENT '문항코드',
  `UPR_QITEM_CD` varchar(20) DEFAULT NULL COMMENT '상위문항코드',
  `EVL_SCR` decimal(5,2) DEFAULT NULL COMMENT '평가점수',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='활동답변상세정보';


-- ESG_DB.ACT_TGT_QITEM_INFO definition

CREATE TABLE `ACT_TGT_QITEM_INFO` (
  `ACT_TGT_CD` varchar(20) NOT NULL COMMENT '활동대상코드',
  `STEP_CD` varchar(20) NOT NULL COMMENT '단계코드',
  `QITEM_GRP_CD` varchar(20) NOT NULL COMMENT '문항그룹코드',
  `QITEM_CD` varchar(20) NOT NULL COMMENT '문항코드',
  `UPR_QITEM_CD` varchar(20) DEFAULT NULL COMMENT '상위문항코드',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`ACT_TGT_CD`,`STEP_CD`,`QITEM_GRP_CD`,`QITEM_CD`),
  UNIQUE KEY `ACT_TGT_QITEM_INFO_PK` (`ACT_TGT_CD`,`STEP_CD`,`QITEM_GRP_CD`,`QITEM_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='활동대상문항정보';


-- ESG_DB.BT_ASK_ST_GRP_AGGR definition

CREATE TABLE `BT_ASK_ST_GRP_AGGR` (
  `ASK_ST_CD` varchar(20) NOT NULL COMMENT '문의상태코드',
  `CNT` smallint(5) NOT NULL DEFAULT '0' COMMENT '건수',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`ASK_ST_CD`),
  UNIQUE KEY `BT_ASK_ST_GRP_AGGR_PK` (`ASK_ST_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='문의상태별집계';


-- ESG_DB.BT_DTE_GRP_AGGR definition

CREATE TABLE `BT_DTE_GRP_AGGR` (
  `DAILY_DTE` char(8) NOT NULL COMMENT '일별일자',
  `ASK_CNT` int(11) NOT NULL DEFAULT '0' COMMENT '문의건수',
  `NEWS_CNT` int(11) NOT NULL DEFAULT '0' COMMENT '뉴스건수',
  `JOIN_CNT` int(11) NOT NULL DEFAULT '0' COMMENT '가입건수',
  `PV_CNT` int(11) NOT NULL COMMENT 'Page View 건수',
  `UV_CNT` int(11) NOT NULL COMMENT 'Unique Visitor 건수',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최종수정아이디',
  PRIMARY KEY (`DAILY_DTE`),
  UNIQUE KEY `BT_DTE_GRP_AGGR_PK` (`DAILY_DTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='일자별집계';


-- ESG_DB.BT_RSS_INFO definition

CREATE TABLE `BT_RSS_INFO` (
  `LINK_URL` varchar(500) NOT NULL COMMENT '링크주소',
  `SPLY_BZENTY_CD` varchar(20) NOT NULL COMMENT '제공업체코드',
  `PBLCN_DT` datetime DEFAULT NULL COMMENT '발행일',
  `TTL` varchar(100) NOT NULL COMMENT '제목',
  `SUMRY` varchar(1000) DEFAULT NULL COMMENT '요약',
  `CN` text NOT NULL COMMENT '내용',
  `IMG_URL` varchar(250) DEFAULT NULL COMMENT '이미지URL',
  `WRTR_NM` varchar(50) DEFAULT NULL COMMENT '작성자명',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최종수정아이디',
  PRIMARY KEY (`LINK_URL`),
  UNIQUE KEY `BT_RSS_INFO_PK` (`LINK_URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='RSS정보';


-- ESG_DB.CM_ATAC_DTL_INFO definition

CREATE TABLE `CM_ATAC_DTL_INFO` (
  `ATAC_FILE_UID` int(15) NOT NULL COMMENT '첨부파일채번',
  `ATAC_DTL_UID` int(15) NOT NULL COMMENT '첨부상세채번',
  `ATAC_TP_CD` varchar(20) NOT NULL COMMENT '첨부유형코드',
  `FILE_PRC_ST_CD` varchar(20) NOT NULL COMMENT '파일처리상태코드',
  `DP_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '전시여부',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `ORGNL_FILE_NM` varchar(250) NOT NULL COMMENT '원본파일명',
  `ORGNL_EXTN` varchar(10) NOT NULL COMMENT '원본확장자',
  `ORGNL_FILE_SZ` decimal(15,0) NOT NULL COMMENT '원본파일크기',
  `ORGNL_FILE_FPATH` varchar(250) NOT NULL COMMENT '원본파일전체경로',
  `CNVN_FILE_NM` varchar(250) DEFAULT NULL COMMENT '변환파일명',
  `CNVN_EXTN` varchar(10) DEFAULT NULL COMMENT '변환확장자',
  `CNVN_FILE_SZ` decimal(15,0) DEFAULT NULL COMMENT '변환파일크기',
  `CNVN_FILE_FPATH` varchar(1000) DEFAULT NULL COMMENT '변환파일전체경로',
  `TUMNL_FPATH` varchar(250) DEFAULT NULL COMMENT '썸네일전체경로',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`ATAC_FILE_UID`,`ATAC_DTL_UID`),
  UNIQUE KEY `CM_ATAC_DTL_INFO_PK` (`ATAC_FILE_UID`,`ATAC_DTL_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='첨부상세정보';


-- ESG_DB.CM_ATAC_FILE_INFO definition

CREATE TABLE `CM_ATAC_FILE_INFO` (
  `ATAC_FILE_UID` int(15) NOT NULL COMMENT '첨부파일채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  PRIMARY KEY (`ATAC_FILE_UID`),
  UNIQUE KEY `CM_ATAC_FILE_INFO_PK` (`ATAC_FILE_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='첨부파일정보';


-- ESG_DB.CM_AUTHRT_INFO definition

CREATE TABLE `CM_AUTHRT_INFO` (
  `AUTHRT_UID` int(15) NOT NULL COMMENT '권한채번',
  `AUTHRT_UNO` varchar(20) NOT NULL COMMENT '권한고유번호',
  `AUTHRT_NM` varchar(50) NOT NULL COMMENT '권한명',
  `AUTHRT_COMNT` varchar(1000) DEFAULT NULL COMMENT '권한설명',
  `DP_SEQ` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전시순서',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`AUTHRT_UID`),
  UNIQUE KEY `CM_AUTHRT_INFO_PK` (`AUTHRT_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='권한정보';


-- ESG_DB.CM_COMM_CD_INFO definition

CREATE TABLE `CM_COMM_CD_INFO` (
  `GRP_CD` varchar(20) NOT NULL COMMENT '그룹코드',
  `CD` varchar(20) NOT NULL COMMENT '코드',
  `CD_NM` varchar(250) NOT NULL COMMENT '코드명',
  `DP_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '전시여부',
  `DP_SEQ` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전시순서',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `LVL` decimal(2,0) NOT NULL DEFAULT '0' COMMENT '뎁스',
  `UPR_GRP_CD` varchar(20) DEFAULT NULL COMMENT '상위그룹코드',
  `UPR_CD` varchar(20) DEFAULT NULL COMMENT '상위코드',
  `CD_COMT` varchar(1000) DEFAULT NULL COMMENT '코드설명',
  `REF_1_CD` varchar(20) DEFAULT NULL COMMENT '참조1코드',
  `REF_2_CD` varchar(20) DEFAULT NULL COMMENT '참조2코드',
  `REF_3_CD` varchar(20) DEFAULT NULL COMMENT '참조3코드',
  `REF_4_CD` varchar(20) DEFAULT NULL COMMENT '참조4코드',
  `REF_1_CD_NM` varchar(250) DEFAULT NULL COMMENT '참조1코드명',
  `REF_2_CD_NM` varchar(250) DEFAULT NULL COMMENT '참조2코드명',
  `REF_3_CD_NM` varchar(250) DEFAULT NULL COMMENT '참조3코드명',
  `REF_4_CD_NM` varchar(250) DEFAULT NULL COMMENT '참조4코드명',
  `REF_1_CD_COMT` varchar(1000) DEFAULT NULL COMMENT '참조1코드설명',
  `REF_2_CD_COMT` varchar(1000) DEFAULT NULL COMMENT '참조2코드설명',
  `REF_3_CD_COMT` varchar(1000) DEFAULT NULL COMMENT '참조3코드설명',
  `REF_4_CD_COMT` varchar(1000) DEFAULT NULL COMMENT '참조4코드설명',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`GRP_CD`,`CD`),
  UNIQUE KEY `CM_COMM_CD_INFO_PK` (`GRP_CD`,`CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공통코드정보';


-- ESG_DB.CM_COPR_INFO definition

CREATE TABLE `CM_COPR_INFO` (
  `COPR_UID` int(15) NOT NULL AUTO_INCREMENT COMMENT '소속채번',
  `COPR_UNO` varchar(20) NOT NULL COMMENT '소속고유번호',
  `COPR_NM` varchar(50) NOT NULL COMMENT '소속명',
  `BRNO` char(10) DEFAULT NULL COMMENT '사업자등록번호',
  `COPR_PHON_NO` varchar(20) DEFAULT NULL COMMENT '소속전화번호',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`COPR_UID`),
  UNIQUE KEY `CM_COPR_INFO_PK` (`COPR_UID`)
) ENGINE=InnoDB AUTO_INCREMENT=539186 DEFAULT CHARSET=utf8 COMMENT='소속정보';


-- ESG_DB.CM_GRP_CD_INFO definition

CREATE TABLE `CM_GRP_CD_INFO` (
  `GRP_CD` varchar(20) NOT NULL COMMENT '그룹코드',
  `GRP_CD_NM` varchar(250) NOT NULL COMMENT '그룹코드명',
  `DP_SEQ` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전시순서',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `CD_COMT` varchar(1000) DEFAULT NULL COMMENT '코드설명',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`GRP_CD`),
  UNIQUE KEY `CM_GRP_CD_INFO_PK` (`GRP_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='그룹코드정보';


-- ESG_DB.CM_MNGR_INFO definition

CREATE TABLE `CM_MNGR_INFO` (
  `MNGR_UID` int(15) NOT NULL COMMENT '관리자채번',
  `MNGR_UNO` varchar(20) NOT NULL COMMENT '관리자고유번호',
  `MNGR_ID` varchar(100) NOT NULL COMMENT '관리자아이디',
  `MNGR_PWD` varchar(300) NOT NULL COMMENT '관리자암호',
  `MNGR_ST_CD` varchar(20) NOT NULL COMMENT '관리자상태코드',
  `MNGR_NM` varchar(50) NOT NULL COMMENT '관리자명',
  `MNGR_MAIL` varchar(50) NOT NULL COMMENT '관리자이메일',
  `JOIN_DT` datetime NOT NULL COMMENT '가입일',
  `WHDWL_APLY_DT` datetime DEFAULT NULL COMMENT '탈퇴신청일',
  `WHDWL_APRV_DT` datetime DEFAULT NULL COMMENT '탈퇴승인일',
  `CPHON_NO` varchar(20) NOT NULL COMMENT '휴대폰번호',
  `MAIL_CHK_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '이메일확인여부',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`MNGR_UID`),
  UNIQUE KEY `CM_MNGR_INFO_PK` (`MNGR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='관리자정보';


-- ESG_DB.CM_RSS_BASE_INFO definition

CREATE TABLE `CM_RSS_BASE_INFO` (
  `SPLY_BZENTY_CD` varchar(20) NOT NULL COMMENT '제공업체코드',
  `SEQ_NO` decimal(5,0) NOT NULL COMMENT '순번',
  `SECTN_NM` varchar(50) NOT NULL COMMENT '섹션명',
  `SECTN_URL` varchar(250) NOT NULL COMMENT '섹션URL',
  `LST_BUILD_DT` varchar(100) NOT NULL COMMENT 'RSS최종작성일',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`SPLY_BZENTY_CD`,`SEQ_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='RSS기준정보';


-- ESG_DB.CS_ANSR_INFO definition

CREATE TABLE `CS_ANSR_INFO` (
  `ANSR_UID` int(15) NOT NULL COMMENT '답변채번',
  `ANSR_CN` text NOT NULL COMMENT '답변내용',
  `ANSR_MEMO` varchar(250) DEFAULT NULL COMMENT '답변메모',
  `ASK_UID` int(15) NOT NULL COMMENT '문의채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`ANSR_UID`),
  UNIQUE KEY `CS_ANSR_INFO_PK` (`ANSR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='답변정보';


-- ESG_DB.CS_ASK_INFO definition

CREATE TABLE `CS_ASK_INFO` (
  `ASK_UID` int(15) NOT NULL COMMENT '문의채번',
  `ASK_TP_CD` varchar(20) NOT NULL COMMENT '문의유형코드',
  `ASK_TTL` varchar(100) NOT NULL COMMENT '문의제목',
  `ASK_ST_CD` varchar(20) NOT NULL COMMENT '문의상태코드',
  `ASK_CN` text NOT NULL COMMENT '문의내용',
  `MBR_ID` varchar(100) NOT NULL COMMENT '회원아이디',
  `ASK_MAIL` varchar(50) DEFAULT NULL COMMENT '문의이메일',
  `COMP_NM` varchar(50) DEFAULT NULL COMMENT '회사명',
  `COPR_UID` int(15) DEFAULT NULL COMMENT '소속채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  `MBR_UID` int(15) DEFAULT NULL COMMENT '회원채번',
  `ACT_TGT_CD` varchar(20) DEFAULT NULL COMMENT '활동대상코드',
  PRIMARY KEY (`ASK_UID`),
  UNIQUE KEY `CS_ASK_INFO_PK` (`ASK_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='문의정보';


-- ESG_DB.CS_SCHDL_INFO definition

CREATE TABLE `CS_SCHDL_INFO` (
  `SCHDL_UID` int(15) NOT NULL COMMENT '일정채번',
  `SCHDL_TTL` varchar(100) NOT NULL COMMENT '일정제목',
  `SCHDL_TP_CD` varchar(20) NOT NULL COMMENT '일정유형코드',
  `SCHDL_GB_CD` varchar(20) NOT NULL COMMENT '일정구분코드',
  `SCHDL_DTE` char(8) NOT NULL COMMENT '일정일자',
  `UDTMN_SCHDL_MM_CD` varchar(20) DEFAULT NULL COMMENT '미확정일정월코드',
  `UDTMN_SCHDL_QT_CD` varchar(20) DEFAULT NULL COMMENT '미확정일정분기코드',
  `REPT_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '반복여부',
  `REPT_UNIT_CD` varchar(20) DEFAULT NULL COMMENT '반복단위코드',
  `REPT_NMTM` smallint(3) DEFAULT NULL COMMENT '반복횟수',
  `REPT_TP_CD` varchar(20) DEFAULT NULL COMMENT '반복유형코드',
  `REPT_END_DT` datetime DEFAULT NULL COMMENT '반복종료일',
  `SCHDL_CN` text COMMENT '일정내용',
  `LINK_URL` varchar(500) DEFAULT NULL COMMENT '링크주소',
  `NWIN_YN` char(1) DEFAULT NULL COMMENT '새창여부',
  `LVL` decimal(2,0) DEFAULT '0' COMMENT '뎁스',
  `UPR_SCHDL_UID` int(15) DEFAULT NULL COMMENT '상위일정채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`SCHDL_UID`),
  UNIQUE KEY `CS_SCHDL_INFO_PK` (`SCHDL_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='일정정보';


-- ESG_DB.DP_CONT_TPIC_INFO definition

CREATE TABLE `DP_CONT_TPIC_INFO` (
  `CONT_UID` int(15) NOT NULL COMMENT '콘텐츠채번',
  `TPIC_UID` int(15) NOT NULL COMMENT '토픽채번',
  `DP_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '전시여부',
  `DP_SEQ` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전시순서',
  `DP_FIX_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '전시고정여부',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`CONT_UID`,`TPIC_UID`),
  UNIQUE KEY `DP_CONT_TPIC_INFO_PK` (`CONT_UID`,`TPIC_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='콘텐츠토픽정보';


-- ESG_DB.DP_TPIC_APND_INFO definition

CREATE TABLE `DP_TPIC_APND_INFO` (
  `TPIC_UID` int(15) NOT NULL COMMENT '토픽채번',
  `TPIC_TP_CD` varchar(20) NOT NULL COMMENT '토픽유형코드',
  `SEQ_NO` decimal(5,0) NOT NULL COMMENT '순번',
  `SUMRY_COMNT` varchar(4000) DEFAULT NULL COMMENT '요약설명',
  `APND_TTL` varchar(100) DEFAULT NULL COMMENT '부가제목',
  `APND_CN` text COMMENT '부가내용',
  `SPCAL_NM` varchar(50) DEFAULT NULL COMMENT '전문가명',
  `SPCAL_POS_NM` varchar(50) DEFAULT NULL COMMENT '전문가직급명',
  `SPCAL_MAIL` varchar(50) DEFAULT NULL COMMENT '전문가이메일',
  `SPCAL_TELNO` varchar(20) DEFAULT NULL COMMENT '전문가전번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`TPIC_UID`,`TPIC_TP_CD`,`SEQ_NO`),
  UNIQUE KEY `DP_TPIC_APND_INFO_PK` (`TPIC_UID`,`TPIC_TP_CD`,`SEQ_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='토픽부가정보';


-- ESG_DB.DP_TPIC_INFO definition

CREATE TABLE `DP_TPIC_INFO` (
  `TPIC_UID` int(15) NOT NULL COMMENT '토픽채번',
  `TPIC_NM` varchar(50) NOT NULL COMMENT '토픽명',
  `TPIC_GB_CD` varchar(20) NOT NULL COMMENT '토픽구분코드',
  `TPIC_MNU_CD` varchar(20) NOT NULL COMMENT '토픽메뉴코드',
  `RLS_TGT_CD_ARRY` varchar(250) DEFAULT NULL COMMENT '공개대상코드배열',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `DP_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '전시여부',
  `DP_SEQ` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전시순서',
  `DP_STT_DT` datetime DEFAULT NULL COMMENT '전시시작일',
  `DP_END_DT` datetime DEFAULT NULL COMMENT '전시종료일',
  `PIRD_STNG_USE_YN` char(1) DEFAULT NULL COMMENT '기간설정사용여부',
  `DP_FIX_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '전시고정여부',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`TPIC_UID`),
  UNIQUE KEY `DP_TPIC_INFO_PK` (`TPIC_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='토픽정보';


-- ESG_DB.DP_TPIC_RLS_TGT_INFO definition

CREATE TABLE `DP_TPIC_RLS_TGT_INFO` (
  `TPIC_UID` int(15) NOT NULL COMMENT '토픽채번',
  `RLS_TGT_CD` varchar(20) NOT NULL COMMENT '공개대상코드',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  PRIMARY KEY (`TPIC_UID`,`RLS_TGT_CD`),
  UNIQUE KEY `DP_TPIC_RLS_TGT_INFO_PK` (`TPIC_UID`,`RLS_TGT_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='토픽공개대상정보';


-- ESG_DB.MB_ACT_ANSR_INFO definition

CREATE TABLE `MB_ACT_ANSR_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `ACT_TGT_CD` varchar(20) NOT NULL COMMENT '활동대상코드',
  `STEP_CD` varchar(20) NOT NULL COMMENT '단계코드',
  `SEQ_NO` decimal(5,0) NOT NULL COMMENT '순번',
  `ACT_ANSR` varchar(100) NOT NULL COMMENT '활동답변',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  `QITEM_GRP_CD` varchar(20) DEFAULT NULL COMMENT '문항그룹코드',
  `QITEM_CD` varchar(20) DEFAULT NULL COMMENT '문항코드',
  `UPR_QITEM_CD` varchar(20) DEFAULT NULL COMMENT '상위문항코드',
  `EVL_SCR` decimal(5,2) DEFAULT '0.00' COMMENT '평가점수',
  PRIMARY KEY (`MBR_UID`,`ACT_TGT_CD`,`STEP_CD`,`SEQ_NO`),
  UNIQUE KEY `MB_ACT_ANSR_INFO_PK` (`MBR_UID`,`ACT_TGT_CD`,`STEP_CD`,`SEQ_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='활동답변정보';


-- ESG_DB.MB_CSRD_TGT_ACT_INFO definition

CREATE TABLE `MB_CSRD_TGT_ACT_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `ACT_TGT_CD` varchar(20) NOT NULL COMMENT '활동대상코드',
  `STEP_CD` varchar(20) NOT NULL COMMENT '단계코드',
  `ACT_STT_DT` datetime NOT NULL COMMENT '활동시작일',
  `ACT_PRGRS_ST_CD` varchar(20) DEFAULT NULL COMMENT '활동진행상태코드',
  `ACT_CMPTN_DT` datetime DEFAULT NULL COMMENT '활동완료일',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`MBR_UID`,`ACT_TGT_CD`,`STEP_CD`),
  UNIQUE KEY `MB_CSRD_TGT_ACT_INFO_PK` (`MBR_UID`,`ACT_TGT_CD`,`STEP_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CSRD대상활동정보';


-- ESG_DB.MB_ESG_TGT_ACT_INFO definition

CREATE TABLE `MB_ESG_TGT_ACT_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `ACT_TGT_CD` varchar(20) NOT NULL COMMENT '활동대상코드',
  `STEP_CD` varchar(20) NOT NULL COMMENT '단계코드',
  `ACT_STT_DT` datetime NOT NULL COMMENT '활동시작일',
  `ACT_PRGRS_ST_CD` varchar(20) DEFAULT NULL COMMENT '활동진행상태코드',
  `ACT_CMPTN_DT` datetime DEFAULT NULL COMMENT '활동완료일',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`MBR_UID`,`ACT_TGT_CD`,`STEP_CD`),
  UNIQUE KEY `MB_ESG_TGT_ACT_INFO_PK` (`MBR_UID`,`ACT_TGT_CD`,`STEP_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ESG대상활동정보';


-- ESG_DB.MB_MBR_ACT_INFO definition

CREATE TABLE `MB_MBR_ACT_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `ACT_TGT_CD` varchar(20) NOT NULL COMMENT '활동대상코드',
  `ACT_ST_CD` varchar(20) NOT NULL COMMENT '활동상태코드',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`MBR_UID`,`ACT_TGT_CD`),
  UNIQUE KEY `MB_MBR_ACT_INFO_PK` (`MBR_UID`,`ACT_TGT_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회원활동정보';


-- ESG_DB.MB_MBR_INFO definition

CREATE TABLE `MB_MBR_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `MBR_UNO` varchar(20) NOT NULL COMMENT '회원고유번호',
  `MBR_ID` varchar(100) NOT NULL COMMENT '회원아이디',
  `MBR_PWD` varchar(300) NOT NULL COMMENT '회원암호',
  `MBR_GB_CD` varchar(20) DEFAULT NULL COMMENT '회원구분코드',
  `MBR_NM` varchar(50) NOT NULL COMMENT '회원명',
  `MBR_ST_CD` varchar(20) NOT NULL COMMENT '회원상태코드',
  `JOIN_DT` datetime NOT NULL COMMENT '가입일',
  `WHDWL_APLY_DT` datetime DEFAULT NULL COMMENT '탈퇴신청일',
  `WHDWL_APRV_DT` datetime DEFAULT NULL COMMENT '탈퇴승인일',
  `DEPT_NM` varchar(50) DEFAULT NULL COMMENT '부서명',
  `POS_NM` varchar(50) DEFAULT NULL COMMENT '직급명',
  `COMP_MAIL` varchar(50) DEFAULT NULL COMMENT '회사이메일',
  `MAIL_CHK_YN` char(1) NOT NULL COMMENT '이메일확인여부',
  `MAIL_CHK_DT` datetime DEFAULT NULL COMMENT '이메일확인일',
  `PWD_FAIL_CNT` decimal(5,0) NOT NULL DEFAULT '0' COMMENT '암호실패건수',
  `PWD_RCTLY_CHNG_DT` datetime DEFAULT NULL COMMENT '암호최근변경일',
  `MRKT_AGRE_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '마케팅동의여부',
  `MRKT_AGRE_DT` datetime DEFAULT NULL COMMENT '마케팅동의일',
  `NSLT_AGRE_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '뉴스레터동의여부',
  `NSLT_AGRE_DT` datetime DEFAULT NULL COMMENT '뉴스레터동의일',
  `INTR_CD_ARRY` varchar(250) DEFAULT NULL COMMENT '관심코드배열',
  `CPHON_NO` varchar(20) DEFAULT NULL COMMENT '휴대폰번호',
  `FAX_NO` varchar(20) DEFAULT NULL COMMENT '팩스번호',
  `COPR_UID` int(15) NOT NULL COMMENT '소속채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  `WHDWL_CAUS_CD` varchar(20) DEFAULT NULL COMMENT '탈퇴사유코드',
  `WHDWL_CAUS_COMNT` varchar(4000) DEFAULT NULL COMMENT '탈퇴사유설명',
  `MAIL_AGRE_YN` char(1) DEFAULT NULL COMMENT '이메일동의여부',
  `MAIL_AGRE_DT` datetime DEFAULT NULL COMMENT '이메일동의일',
  `SMS_AGRE_YN` char(1) DEFAULT NULL COMMENT 'SMS동의여부',
  `SMS_AGRE_DT` datetime DEFAULT NULL COMMENT 'SMS동의일',
  PRIMARY KEY (`MBR_UID`),
  UNIQUE KEY `MB_MBR_INFO_PK` (`MBR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회원정보';


-- ESG_DB.MB_MBR_INFO_20230718 definition

CREATE TABLE `MB_MBR_INFO_20230718` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `MBR_UNO` varchar(20) NOT NULL COMMENT '회원고유번호',
  `MBR_ID` varchar(100) NOT NULL COMMENT '회원아이디',
  `MBR_PWD` varchar(4000) NOT NULL COMMENT '회원암호',
  `MBR_GB_CD` varchar(20) DEFAULT NULL COMMENT '회원구분코드',
  `MBR_NM` varchar(50) NOT NULL COMMENT '회원명',
  `MBR_ST_CD` varchar(20) NOT NULL COMMENT '회원상태코드',
  `JOIN_DT` datetime NOT NULL COMMENT '가입일',
  `WHDWL_APLY_DT` datetime DEFAULT NULL COMMENT '탈퇴신청일',
  `WHDWL_APRV_DT` datetime DEFAULT NULL COMMENT '탈퇴승인일',
  `COMP_NM` varchar(50) DEFAULT NULL COMMENT '회사명',
  `DEPT_NM` varchar(50) DEFAULT NULL COMMENT '부서명',
  `POS_NM` varchar(50) DEFAULT NULL COMMENT '직급명',
  `COMP_MAIL` varchar(50) DEFAULT NULL COMMENT '회사이메일',
  `COMP_PHON_NO` varchar(20) DEFAULT NULL COMMENT '회사전화번호',
  `MAIL_CHK_YN` char(1) NOT NULL COMMENT '이메일확인여부',
  `MAIL_CHK_DT` datetime DEFAULT NULL COMMENT '이메일확인일',
  `PWD_FAIL_CNT` decimal(5,0) NOT NULL DEFAULT '0' COMMENT '암호실패건수',
  `PWD_RCTLY_CHNG_DT` datetime DEFAULT NULL COMMENT '암호최근변경일',
  `MRKT_AGRE_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '마케팅동의여부',
  `MRKT_AGRE_DT` datetime DEFAULT NULL COMMENT '마케팅동의일',
  `NSLT_AGRE_YN` char(1) NOT NULL DEFAULT 'N' COMMENT '뉴스레터동의여부',
  `NSLT_AGRE_DT` datetime DEFAULT NULL COMMENT '뉴스레터동의일',
  `INTR_CD_ARRY` varchar(250) DEFAULT NULL COMMENT '관심코드배열',
  `CPHON_NO` varchar(20) DEFAULT NULL COMMENT '휴대폰번호',
  `FAX_NO` varchar(20) DEFAULT NULL COMMENT '팩스번호',
  `COPR_UID` int(15) NOT NULL COMMENT '소속채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회원정보';


-- ESG_DB.MB_MBR_INTR_INFO definition

CREATE TABLE `MB_MBR_INTR_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `INTR_CD` varchar(20) NOT NULL COMMENT '관심코드',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  PRIMARY KEY (`MBR_UID`,`INTR_CD`),
  UNIQUE KEY `MB_MBR_INTR_INFO_PK` (`MBR_UID`,`INTR_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회원관심정보';


-- ESG_DB.MB_MEMO_INFO definition

CREATE TABLE `MB_MEMO_INFO` (
  `MBR_UID` int(15) NOT NULL COMMENT '회원채번',
  `SEQ_NO` decimal(5,0) NOT NULL COMMENT '순번',
  `MEMO_DESC` text NOT NULL COMMENT '메모내용',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`MBR_UID`,`SEQ_NO`),
  KEY `MB_MEMO_INFO_MBR_UID_IDX` (`MBR_UID`,`SEQ_NO`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='메모정보';


-- ESG_DB.MB_NEWS_SUSC_INFO definition

CREATE TABLE `MB_NEWS_SUSC_INFO` (
  `NEWS_SUSC_UID` int(15) NOT NULL COMMENT '뉴스구독채번',
  `SUSC_ID` varchar(100) NOT NULL COMMENT '구독아이디',
  `SUSC_ST_CD` varchar(20) NOT NULL COMMENT '구독상태코드',
  `SUSC_APLY_DT` datetime NOT NULL COMMENT '구독신청일',
  `SUSC_APLY_PRC_DT` datetime DEFAULT NULL COMMENT '구독신청처리일',
  `SUSC_END_DT` datetime DEFAULT NULL COMMENT '구독종료일',
  `SUSC_MAIL` varchar(50) NOT NULL COMMENT '구독이메일',
  `MAIL_CHK_YN` char(1) NOT NULL COMMENT '이메일확인여부',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`NEWS_SUSC_UID`),
  UNIQUE KEY `MB_NEWS_SUSC_INFO_PK` (`NEWS_SUSC_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='뉴스구독정보';


-- ESG_DB.MB_SUSC_PRC_LOG definition

CREATE TABLE `MB_SUSC_PRC_LOG` (
  `SUSC_PRC_UID` int(15) NOT NULL COMMENT '구독처리채번',
  `SUSC_ST_CD` varchar(20) NOT NULL COMMENT '구독상태코드',
  `NEWS_SUSC_UID` int(15) NOT NULL COMMENT '뉴스구독채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  PRIMARY KEY (`SUSC_PRC_UID`),
  UNIQUE KEY `MB_SUSC_PRC_LOG_PK` (`SUSC_PRC_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='구독처리로그';


-- ESG_DB.ST_ACCS_LOG definition

CREATE TABLE `ST_ACCS_LOG` (
  `ACCS_URI` varchar(250) NOT NULL COMMENT '접속URI',
  `MBR_ID` varchar(100) DEFAULT NULL COMMENT '회원아이디',
  `SESN_ID` varchar(100) DEFAULT NULL COMMENT '세션아이디',
  `DEVICE_TP_CD` varchar(20) DEFAULT NULL COMMENT '디바이스유형코드',
  `INFLW_CHNL_CD` varchar(500) DEFAULT NULL COMMENT '유입채널코드',
  `USR_AGNT` varchar(200) DEFAULT NULL COMMENT '사용자에이젼트',
  `DEVICE_IP` varchar(20) DEFAULT NULL COMMENT '디바이스아이피',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최초등록아이디'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='접속로그';


-- ESG_DB.ST_CONT_APND_INFO definition

CREATE TABLE `ST_CONT_APND_INFO` (
  `CONT_UID` int(15) NOT NULL COMMENT '콘텐츠채번',
  `CONT_KIND_CD` varchar(20) NOT NULL COMMENT '콘텐츠종류코드',
  `SEQ_NO` decimal(5,0) NOT NULL COMMENT '순번',
  `CONT_RMTHD_CD` varchar(20) DEFAULT NULL COMMENT '콘텐츠등록방식코드',
  `LINK_URL` varchar(500) DEFAULT NULL COMMENT '링크주소',
  `NWIN_YN` char(1) DEFAULT NULL COMMENT '새창여부',
  `CONT_SPLY_TP_CD` varchar(20) DEFAULT NULL COMMENT '콘텐츠제공유형코드',
  `VOD_QUNTY_HH` varchar(2) DEFAULT NULL COMMENT '영상분량시',
  `VOD_QUNTY_MI` varchar(2) DEFAULT NULL COMMENT '영상분량분',
  `VOD_QUNTY_SEC` varchar(2) DEFAULT NULL COMMENT '영상분량초',
  `PAGE_CNT` smallint(5) DEFAULT NULL COMMENT '페이지수',
  `LESN_NM` varchar(50) DEFAULT NULL COMMENT '레슨명',
  `VOD_COMNT` varchar(1000) DEFAULT NULL COMMENT '영상설명',
  `ATAC_FILE_UID` int(15) DEFAULT NULL COMMENT '첨부파일채번',
  `ATAC_DTL_UID` int(15) DEFAULT NULL COMMENT '첨부상세채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`CONT_UID`,`CONT_KIND_CD`,`SEQ_NO`),
  UNIQUE KEY `ST_CONT_APND_INFO_PK` (`CONT_UID`,`CONT_KIND_CD`,`SEQ_NO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='콘텐츠부가정보';


-- ESG_DB.ST_CONT_INFO definition

CREATE TABLE `ST_CONT_INFO` (
  `CONT_UID` int(15) NOT NULL COMMENT '콘텐츠채번',
  `CONT_UNO` varchar(20) NOT NULL COMMENT '콘텐츠고유번호',
  `CONT_KIND_CD` varchar(20) NOT NULL COMMENT '콘텐츠종류코드',
  `CONT_RMTHD_CD` varchar(20) DEFAULT NULL COMMENT '콘텐츠등록방식코드',
  `CONT_NM` varchar(100) NOT NULL COMMENT '콘텐츠명',
  `PBLCN_DTE` char(8) DEFAULT NULL COMMENT '발행일자',
  `PBLCN_YY` char(4) DEFAULT NULL COMMENT '발행YY',
  `PBLCN_MM` char(2) DEFAULT NULL COMMENT '발행MM',
  `PBLCN_DD` char(2) DEFAULT NULL COMMENT '발행DD',
  `DMSTC_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '국내여부',
  `SPLY_LANG_CD` varchar(20) NOT NULL COMMENT '제공언어코드',
  `CONT_TP_LCLSF_CD` varchar(20) NOT NULL COMMENT '콘텐츠유형대분류코드',
  `CONT_TP_MCLSF_CD` varchar(20) DEFAULT NULL COMMENT '콘텐츠유형중분류코드',
  `TASK_CLSF_CD` varchar(20) NOT NULL COMMENT '업무분류코드',
  `USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
  `DP_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '전시여부',
  `DP_TP_CD` varchar(20) NOT NULL COMMENT '전시유형코드',
  `DP_STT_DT` datetime DEFAULT NULL COMMENT '전시시작일',
  `DP_END_DT` datetime DEFAULT NULL COMMENT '전시종료일',
  `PIRD_STNG_USE_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '기간설정사용여부',
  `DWNLD_PSBLTY_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '다운로드가능여부',
  `SRCH_PSBLTY_YN` char(1) NOT NULL DEFAULT 'Y' COMMENT '검색가능여부',
  `CONT_SUMRY` varchar(4000) DEFAULT NULL COMMENT '콘텐츠요약',
  `CONT_ST_CD` varchar(20) DEFAULT NULL COMMENT '콘텐츠상태코드',
  `KWRD_ARRY` varchar(250) DEFAULT NULL COMMENT '키워드배열',
  `RLS_TGT_CD_ARRY` varchar(250) DEFAULT NULL COMMENT '공개대상코드배열',
  `SRC_UID` int(15) NOT NULL COMMENT '출처채번',
  `ATAC_FILE_UID` int(15) DEFAULT NULL COMMENT '첨부파일채번',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  `TPIC_MNU_CD` varchar(20) DEFAULT NULL COMMENT '토픽메뉴코드(주제분류)',
  `LINK_URL` varchar(500) DEFAULT NULL COMMENT '링크주소(RSS피드)',
  `PBLCN_GB_CD` varchar(20) DEFAULT NULL COMMENT '발행구분코드',
  `VW_CNT` int(10) NOT NULL DEFAULT '0' COMMENT '조회수',
  PRIMARY KEY (`CONT_UID`),
  UNIQUE KEY `ST_CONT_INFO_PK` (`CONT_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='콘텐츠정보';


-- ESG_DB.ST_CONT_RLS_TGT_INFO definition

CREATE TABLE `ST_CONT_RLS_TGT_INFO` (
  `CONT_UID` int(15) NOT NULL COMMENT '콘텐츠채번',
  `RLS_TGT_CD` varchar(20) NOT NULL COMMENT '공개대상코드',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  PRIMARY KEY (`CONT_UID`,`RLS_TGT_CD`),
  UNIQUE KEY `ST_CONT_RLS_TGT_INFO_PK` (`CONT_UID`,`RLS_TGT_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='콘텐츠공개대상정보';


-- ESG_DB.ST_KWRD_INFO definition

CREATE TABLE `ST_KWRD_INFO` (
  `CONT_UID` int(15) NOT NULL COMMENT '콘텐츠채번',
  `TAG_KWRD` varchar(250) NOT NULL COMMENT '태그키워드',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `DP_SEQ` decimal(3,0) NOT NULL DEFAULT '0' COMMENT '전시순서',
  PRIMARY KEY (`CONT_UID`,`TAG_KWRD`),
  UNIQUE KEY `ST_KWRD_INFO_PK` (`CONT_UID`,`TAG_KWRD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='키워드정보';


-- ESG_DB.ST_SESN_ACCS_LOG definition

CREATE TABLE `ST_SESN_ACCS_LOG` (
  `SESN_ID` varchar(100) NOT NULL COMMENT '세션아이디',
  `MBR_ID` varchar(100) DEFAULT NULL COMMENT '회원아이디',
  `LOGIN_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '로그인일',
  `LOGOUT_DT` datetime DEFAULT NULL COMMENT '로그아웃일',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL DEFAULT 'SYSTEM' COMMENT '최종수정아이디'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='세션접속로그';


-- ESG_DB.ST_SRC_INFO definition

CREATE TABLE `ST_SRC_INFO` (
  `SRC_UID` int(15) NOT NULL COMMENT '출처채번',
  `SRC_UNO` varchar(20) NOT NULL COMMENT '출처고유번호',
  `SRC_NM` varchar(50) NOT NULL COMMENT '출처명',
  `DMSTC_YN` char(1) NOT NULL COMMENT '국내여부',
  `FST_INS_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최초등록일',
  `FST_INS_ID` varchar(100) NOT NULL COMMENT '최초등록아이디',
  `LST_UPD_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '최종수정일',
  `LST_UPD_ID` varchar(100) NOT NULL COMMENT '최종수정아이디',
  PRIMARY KEY (`SRC_UID`),
  UNIQUE KEY `ST_SRC_INFO_PK` (`SRC_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='출처정보';


-- ESG_DB.sequences definition

CREATE TABLE `sequences` (
  `NAME` varchar(32) DEFAULT NULL,
  `CURRVAL` bigint(20) unsigned DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;